import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpen,CheckCircle2,Search} from 'lucide-react';
import {slides} from './slides';
import {SlideContent} from './App';
import {HndlExplorer,Readiness} from './Interactive';
import {modules,milestones,sources} from './researchData';
import './research.css';

export function SourceLinks({items}){return <aside className="research-sources"><b>Sumber & bacaan</b><ul>{items.map(x=><li key={x.url}><a href={x.url} target="_blank" rel="noreferrer">{x.title} ↗</a></li>)}</ul></aside>}
function Section({title,children}){return <section className="research-section"><h2>{title}</h2>{children}</section>}
function Details({items}){return <div className="research-details">{items.map(([title,text])=><details key={title}><summary>{title}</summary><p>{text}</p></details>)}</div>}
function Milestones(){const [active,setActive]=useState(0);const m=milestones[active];return <Section title="Alur perkembangan · Milestone 01–08"><p>Pilih tahap untuk melihat penjelasan, bukti, dan batas kesimpulannya. Periode saling tumpang tindih karena riset berjalan bersamaan.</p><div className="milestone-grid">{milestones.map((x,i)=><button key={x.name} aria-pressed={active===i} aria-controls="milestone-detail" onClick={()=>setActive(i)}><small>{String(i+1).padStart(2,'0')} · {x.period}</small><b>{x.name}</b><span>{x.brief}</span></button>)}</div><article id="milestone-detail" className="milestone-detail" aria-live="polite"><span className="dash-kicker">MILESTONE {String(active+1).padStart(2,'0')} / 08</span><h3>{m.name} · {m.period}</h3><p>{m.detail}</p><SourceLinks items={m.refs}/></article></Section>}
function BankingVenn(){const [view,setView]=useState('intersection');const texts={capability:'Quantum algorithms menawarkan pendekatan untuk simulation, optimisation, sampling dan estimation. Shor juga mengubah asumsi keamanan pada skema public-key tertentu.',banking:'Bank memakai financial modelling, portfolio management, risk analysis, transaksi digital, key establishment dan digital signatures. Dependensi aktual perlu diperiksa per sistem.',intersection:'Dual relevance: peluang perhitungan pada use cases yang sesuai, sekaligus ancaman terhadap security & trust infrastructure yang bergantung pada algoritma rentan.'};return <Section title="Quantum–Banking Intersection"><p>Pilih tombol di bawah diagram untuk membuka penjelasan tiap area. Diagram ini sintesis konseptual dari literatur; luas lingkaran tidak menyatakan jumlah atau besar risiko.</p><svg className="banking-venn" viewBox="0 0 800 350" role="img" aria-label="Dua lingkaran beririsan: emerging quantum capabilities dan banking activities and infrastructure; irisannya dual relevance for banking"><circle cx="285" cy="173" r="155" fill="#1b858933" stroke="#258b90" strokeWidth="2"/><circle cx="515" cy="173" r="155" fill="#da9a3833" stroke="#b97c23" strokeWidth="2"/><text x="245" y="138"><tspan x="245">Emerging quantum</tspan><tspan x="245" dy="27">capabilities</tspan><tspan x="245" dy="38" className="venn-small">Algorithms · computation</tspan></text><text x="555" y="138"><tspan x="555">Banking activities</tspan><tspan x="555" dy="27">& infrastructure</tspan><tspan x="555" dy="38" className="venn-small">Use cases · security</tspan></text><text x="400" y="145" className="venn-center"><tspan x="400">Dual</tspan><tspan x="400" dy="25">relevance</tspan><tspan x="400" dy="34">Benefit</tspan><tspan x="400" dy="23">+ Threat</tspan></text></svg><div className="research-options">{[['capability','Quantum capabilities'],['intersection','Irisan: dual relevance'],['banking','Banking infrastructure']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div><p className="research-note" aria-live="polite">{texts[view]}</p><SourceLinks items={sources.finance}/></Section>}
function Relevance(){return <><Section title="Mengapa mulai dipahami sekarang?"><Details items={[
 ['Technological progress','Fidelity menggambarkan kedekatan operasi atau state dengan target ideal; QEC dan logical error suppression menilai perlindungan informasi. Jumlah qubit saja tidak membuktikan kemampuan menyelesaikan masalah bisnis.'],
 ['Computational frontier','Algoritma kuantum mengubah biaya komputasi pada kelas masalah tertentu. Data loading, noise, biaya oracle, dan post-processing harus dihitung dalam benchmark end-to-end.'],
 ['Banking intersection','Perbankan memiliki kebutuhan komputasi sekaligus infrastruktur kepercayaan digital. Karena itu, pengkajian manfaat dan inventarisasi eksposur keamanan perlu berjalan beriringan.']
 ]}/><p className="research-note">Understand early ≠ adopt immediately.</p><SourceLinks items={[...sources.finance,milestones[6].refs[1]]}/></Section><BankingVenn/><Section title="Dual relevance · dari potensi ke implikasi"><div className="dual-research"><div><h3>Potential benefits</h3><Details items={[
 ['Portfolio optimisation','Mencari alokasi dengan kendala tertentu; QAOA dan metode variational perlu dibandingkan dengan optimiser klasik yang kuat.'],['Risk modelling & derivatives pricing','Amplitude estimation berpotensi mengurangi query untuk estimasi nilai harapan pada asumsi akses yang sesuai. Keuntungan teoretis tidak menghapus biaya menyiapkan distribusi dan circuit.'],['Simulation & financial analytics','Simulasi stokastik dan selected machine learning diteliti untuk problem finansial. Manfaat produksi perlu dibuktikan dengan akurasi, runtime, biaya, dan benchmark klasik.']]}/></div><div><h3>Emerging risk implications</h3><Details items={[
 ['Future cryptanalytic threat','CRQC yang memadai berpotensi menyerang RSA, DH dan ECC; dampaknya mencakup kerahasiaan dan kepercayaan digital.'],['Adoption & model risk','Sebagai implikasi kajian, hasil eksperimen perlu diuji: kualitas data, validitas model, reproducibility dan klaim advantage.'],['Transition & interoperability risk','Migrasi kriptografi melibatkan protokol, sertifikat, vendor dan layanan kritis. Perubahan harus diuji agar fungsi keamanan dan layanan tetap berjalan.']]}/></div></div><SourceLinks items={sources.finance}/><p className="research-note"><b>Mengapa lanjut ke Future Cryptanalytic Threat?</b> BIS Papers No. 149 menyoroti ancaman quantum terhadap kriptografi yang menopang sistem keuangan. Ketergantungan ini membuat keamanan digital menjadi fokus berikutnya, termasuk data yang harus tetap rahasia dalam jangka panjang.</p></Section></>}
function Crypto(){const [scheme,setScheme]=useState('RSA');const map={RSA:['Integer factorisation','Key establishment berbasis RSA dapat mengekspos session key; pemalsuan RSA signatures mengancam autentikasi dan integritas.'],DH:['Discrete logarithm pada finite field','Pemulihan secret dari pertukaran kunci rentan dapat membuka data sesi jika rekaman dan parameter yang diperlukan tersedia.'],ECC:['Elliptic-curve discrete logarithm','ECDH terkait key establishment; ECDSA terkait digital signatures. Dampaknya mengikuti fungsi, bukan sekadar nama ECC.'],'AES / HMAC':['Symmetric cryptography & hash','Bukan target Shor. Grover memberi perubahan generik yang berbeda, dengan biaya fisik besar. AES-256 dan HMAC tidak boleh disamakan dengan RSA/ECC.']};return <><Section title="Future capability → cryptographic impact"><p><b>CRQC (Cryptographically Relevant Quantum Computer)</b> berarti komputer kuantum dengan sumber daya dan kualitas operasi yang cukup untuk menyerang kriptografi pada ukuran kunci yang relevan. Demonstrasi logical qubit atau factoring bilangan kecil belum membuktikan kemampuan tersebut.</p><p>Dengan CRQC yang memadai, Shor dapat menyelesaikan factoring dan discrete logarithms secara polynomial-time. Jalurnya: kemampuan perangkat → penyelesaian masalah matematika → serangan pada skema rentan → dampak pada fungsi keamanan.</p><div className="research-options">{Object.keys(map).map(x=><button key={x} aria-pressed={scheme===x} onClick={()=>setScheme(x)}>{x}</button>)}</div><article className="research-note" aria-live="polite"><h3>{scheme} · {map[scheme][0]}</h3><p>{map[scheme][1]}</p></article><SourceLinks items={[...sources.crypto,sources.finance[1]]}/></Section><Section title="Existing cryptographic dependency"><Details items={[
 ['Payments & APIs → confidentiality','Enkripsi data sering memakai symmetric key; public-key key establishment dapat digunakan untuk menyepakati atau melindungi key tersebut. Memecahkan jalur key establishment dapat berdampak pada data terenkripsi.'],['Authentication → identity & integrity','Digital signatures dan certificates membantu memverifikasi identitas serta keaslian software/transaksi. Risiko forgery berbeda dari dekripsi ciphertext lama.'],['Bukti exposure bank','Contoh fungsi ini bukan hasil audit bank tertentu. Verifikasi algoritma, parameter, protokol, HSM/KMS, certificate chain, library dan vendor dalam inventory.']]}/></Section><Section title="Conditional cryptographic exposure"><Details items={[
 ['1. Actual deployment','Algoritma apa yang benar-benar aktif? Di aplikasi, protokol, perangkat, library atau layanan pihak ketiga mana?'],['2. Cryptographic function','Apakah untuk confidentiality, key establishment, signatures, authentication atau integrity? Fungsi menentukan jalur dampaknya.'],['3. Data & system characteristics','Berapa masa kerahasiaan data, apakah trafik dapat direkam, seberapa kritis layanan, dan berapa lama migrasinya?']]}/><p className="research-note"><b>Jembatan ke HNDL:</b> ketika ciphertext dan informasi pertukaran kunci yang cukup dapat direkam sekarang, data berumur rahasia panjang berpotensi dibuka kemudian dengan CRQC. Ini skenario bersyarat, bukan klaim bahwa seluruh enkripsi sudah dapat dibobol.</p><SourceLinks items={[...sources.crypto,...sources.readiness.slice(0,2)]}/></Section></>}
function Inventory(){const [checked,setChecked]=useState([]);return <Section title="Why inventory comes first"><p>Checklist belajar: tandai elemen yang sudah Anda pahami. Ini tidak menyatakan bahwa inventory bank telah selesai.</p><div className="inventory-checks">{slides[16].items.map(item=><label key={item}><input type="checkbox" checked={checked.includes(item)} onChange={()=>setChecked(v=>v.includes(item)?v.filter(x=>x!==item):[...v,item])}/>{item}</label>)}</div><p aria-live="polite">{checked.length} / {slides[16].items.length} elemen dipahami.</p><SourceLinks items={sources.readiness.slice(0,2)}/></Section>}
function Hndl(){return <><Section title="Harvest Now, Decrypt Later"><p>Ikuti tahapan penyerang dan ubah asumsi X, Y, Z. Angka berasal dari skenario edukatif, bukan estimasi kedatangan CRQC.</p><HndlExplorer items={slides[12].items}/><p className="research-note">X = masa kerahasiaan data; Y = waktu migrasi; Z = waktu menuju CRQC. X + Y &gt; Z adalah alat menilai kebutuhan persiapan. X + Y ≤ Z tidak membuktikan keamanan. Migrasi tidak menghapus ciphertext yang sudah dimiliki penyerang.</p><SourceLinks items={[...sources.crypto,...sources.readiness.slice(0,2)]}/></Section><Section title="From HNDL to quantum readiness"><Details items={[
 ['Adversary: capture → store → potential decryption','Penyerang memerlukan data dan material protokol yang memadai, serta kemampuan menyerang skema yang digunakan. Dekripsi masa depan tetap bersyarat.'],['Bank: identify → plan → test → migrate','Identifikasi data dan skema yang terekspos, tetapkan prioritas, uji solusi dan migrasikan bertahap. Tujuannya mengurangi rekaman baru yang masih bergantung pada skema rentan.']]}/></Section><Section title="What will we do?"><Details items={slides[14].items.map((x,i)=>[x[0],[ 'People: tetapkan owner, latih tim teknologi dan risiko, serta sepakati tanggung jawab.','Technology: inventarisasi kriptografi dan petakan opsi migrasi, termasuk pengujian HSM/KMS.','Policies & processes: masukkan prioritas, pengadaan, perubahan, rollback dan assurance dalam rencana.','Coordination: selaraskan kesiapan vendor, mitra transaksi dan ekosistem.'][i]])}/></Section><Section title="Quantum readiness lifecycle"><Readiness items={slides[15].items}/><SourceLinks items={sources.readiness}/></Section><Inventory/><Section title="Risk-based prioritisation"><Details items={slides[17].rows.map(x=>[x[0],`${x[1]} — ${x[2]}.`])}/><SourceLinks items={sources.readiness}/></Section></>}
export default function Research({moduleId,onNavigate,onDashboard,onLab}){
 const [query,setQuery]=useState('');const [done,setDone]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('quantum-modules-v1')||'[]');return Array.isArray(v)?v:[]}catch{return []}});const heading=useRef(null);
 const index=Math.max(0,modules.findIndex(x=>x.id===moduleId));const mod=modules[index];
 useEffect(()=>{heading.current?.focus();window.scrollTo(0,0)},[moduleId]);
 const mark=()=>{const next=[...new Set([...done,mod.id])];setDone(next);try{localStorage.setItem('quantum-modules-v1',JSON.stringify(next))}catch{/* Reading remains usable without storage. */}};
 return <div className="research"><label className="research-search"><Search size={18}/><input aria-label="Cari modul kajian" value={query} placeholder="Cari modul, fitur, atau topik…" onChange={e=>setQuery(e.target.value)}/></label><nav className="module-nav" aria-label="Modul kajian">{modules.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).map(x=><button key={x.id} aria-current={x.id===mod.id?'page':undefined} onClick={()=>onNavigate(x.id)}>{done.includes(x.id)&&<CheckCircle2 size={15}/>} {x.name}</button>)}</nav>{!modules.some(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))&&<p>Tidak ada modul yang cocok. Coba kata kunci lain.</p>}<header className="module-heading"><p>MODUL {index+1} / {modules.length} · MATERI {mod.start}–{mod.end}</p><h1 tabIndex="-1" ref={heading}>{mod.name}</h1><p>{mod.summary}</p><span><BookOpen size={16}/> {mod.feature}</span></header>
 {mod.id==='evolution'&&<><Section title={slides[1].title}><p>Quantum Information Foundations menuju Adaptive Error Correction: telusuri perubahan konsep, algoritma, perangkat dan kualitas operasi melalui delapan milestone berikut.</p></Section><Milestones/></>}
 {mod.id==='relevance'&&<Relevance/>}{mod.id==='cryptography'&&<Crypto/>}{mod.id==='hndl'&&<Hndl/>}
 {['foundations','benchmark'].includes(mod.id)&&<>{slides.slice(mod.start-1,mod.end).map((s,i)=><div className="slide reading-slide" key={s.title}><SlideContent slide={s}/>{s.source&&<SourceLinks items={mod.id==='benchmark'?sources.readiness:[...sources.finance,...sources.crypto]}/>}</div>)}<button className="dash-primary" onClick={onLab}>Eksplorasi konsep di Computing Lab <ArrowRight size={17}/></button></>}
 <footer className="module-footer">{mod.id==='evolution'?<><h2>{slides[5].title}</h2><p>Rangkaian milestone menunjukkan jalur dari teori menuju demonstrasi terbatas dan QEC yang semakin andal. Bukti tiap tahap perlu dibaca sesuai tugas dan skala eksperimennya; keberhasilan satu tahap tidak otomatis berarti CRQC telah tersedia.</p></>:<><h2>Hubungkan dengan materi berikutnya</h2><p>{mod.id==='relevance'?'Selanjutnya: mengapa public-key cryptography menjadi fokus ancaman.':mod.id==='cryptography'?'Selanjutnya: bagaimana rekaman hari ini dapat menimbulkan exposure di masa depan.':mod.id==='hndl'?'Selanjutnya: pahami state, operasi, dan measurement yang mendasari kemampuan quantum computing.':'Gunakan sumber dan eksperimen untuk menguji pemahaman Anda.'}</p></>}<div className="research-options"><button onClick={onDashboard}>← Kembali ke dashboard</button><button onClick={mark}>{done.includes(mod.id)?'✓ Modul ditandai selesai':'Tandai selesai dibaca'}</button>{modules[index+1]&&<button className="next-module" onClick={()=>onNavigate(modules[index+1].id)}>Lanjut: {modules[index+1].name} →</button>}</div></footer>
 </div>
}
